server:
  port: 9090
spring:
  web:
    resources:
      static-locations: classpath:/templates, classpath:/static
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.200.200.212:3306/mydb?severTimezone=Asia/Seoul
    username: mysqluser
    password: user1234




